/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpEmail {
        "errorMessage": string;
        "inputLabel": string;
        "invalid": boolean;
    }
    interface IpPassword {
        "errorMessage": string;
        "forgotPasswordLink": string;
        "invalid": boolean;
    }
}
declare global {
    interface HTMLIpEmailElement extends Components.IpEmail, HTMLStencilElement {
    }
    var HTMLIpEmailElement: {
        prototype: HTMLIpEmailElement;
        new (): HTMLIpEmailElement;
    };
    interface HTMLIpPasswordElement extends Components.IpPassword, HTMLStencilElement {
    }
    var HTMLIpPasswordElement: {
        prototype: HTMLIpPasswordElement;
        new (): HTMLIpPasswordElement;
    };
    interface HTMLElementTagNameMap {
        "ip-email": HTMLIpEmailElement;
        "ip-password": HTMLIpPasswordElement;
    }
}
declare namespace LocalJSX {
    interface IpEmail {
        "errorMessage"?: string;
        "inputLabel"?: string;
        "invalid"?: boolean;
    }
    interface IpPassword {
        "errorMessage"?: string;
        "forgotPasswordLink"?: string;
        "invalid"?: boolean;
    }
    interface IntrinsicElements {
        "ip-email": IpEmail;
        "ip-password": IpPassword;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-email": LocalJSX.IpEmail & JSXBase.HTMLAttributes<HTMLIpEmailElement>;
            "ip-password": LocalJSX.IpPassword & JSXBase.HTMLAttributes<HTMLIpPasswordElement>;
        }
    }
}
